import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate, useSearchParams } from "react-router-dom";
import {
  AlertTriangle,
  Bell,
  Building2,
  CheckCircle2,
  CreditCard,
  ExternalLink,
  Link2,
  Lock,
  Mail,
  Plug,
  RefreshCw,
  Save,
  Shield,
  Trash2,
  Upload,
  UserRound,
  UserPlus,
  Users,
} from "lucide-react";

import api from "../api/axios";
import { authSuccess } from "../Features/Auth/UserSlice";
import { CardSkeleton } from "../components/ui/Skeleton";

const API_BASE = import.meta.env.VITE_API_URL || "/api";

const sections = [
  { id: "profile", label: "Profile", icon: UserRound },
  { id: "workspace", label: "Workspace", icon: Building2 },
  { id: "team", label: "Team", icon: Users },
  { id: "meta-connections", label: "Meta Integration", icon: Plug },
  { id: "report-defaults", label: "Email Settings", icon: Mail },
  { id: "notifications", label: "Notifications", icon: Bell },
  { id: "security", label: "Security", icon: Shield },
  { id: "billing", label: "Billing", icon: CreditCard },
];

const currencies = ["INR", "USD", "EUR", "GBP", "AED", "AUD", "CAD"];
const timezones = [
  "Asia/Kolkata",
  "America/New_York",
  "America/Los_Angeles",
  "Europe/London",
  "Europe/Berlin",
  "Asia/Dubai",
  "Asia/Singapore",
  "Australia/Sydney",
];
const weekdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const badgeStyles = {
  active: "border-emerald-200 bg-emerald-50 text-emerald-700",
  stable: "border-emerald-200 bg-emerald-50 text-emerald-700",
  trial: "border-sky-200 bg-sky-50 text-sky-700",
  expiring_soon: "border-amber-200 bg-amber-50 text-amber-700",
  moderate: "border-amber-200 bg-amber-50 text-amber-700",
  expired: "border-rose-200 bg-rose-50 text-rose-700",
  permission_error: "border-orange-200 bg-orange-50 text-orange-700",
  critical: "border-rose-200 bg-rose-50 text-rose-700",
  revoked: "border-slate-200 bg-slate-100 text-slate-600",
  removed: "border-slate-200 bg-slate-100 text-slate-600",
  unknown: "border-slate-200 bg-slate-50 text-slate-600",
  unassigned: "border-violet-200 bg-violet-50 text-violet-700",
  owner: "border-slate-900 bg-slate-900 text-white",
  member: "border-slate-200 bg-white text-slate-600",
  pending: "border-amber-200 bg-amber-50 text-amber-700",
};

const metaStatusLabels = {
  active: "Active",
  expiring_soon: "Expiring soon",
  expired: "Expired",
  permission_error: "Permission issue",
  revoked: "Revoked",
  unknown: "Unknown",
};

const defaultMetaOverview = {
  connectedProfilesCount: 0,
  syncedAdAccountsCount: 0,
  needsAttentionCount: 0,
  affectedReportsCount: 0,
};

const defaultProfile = {
  full_name: "",
  email: "",
  currency: "INR",
  avatar_url: "",
};

const defaultWorkspace = {
  name: "",
  slug: "",
  logo_url: "",
  default_sender_name: "Narrative Reports",
  reply_to_email: "",
  from_email: "reports@narrative.app",
  custom_domain_status: "coming_soon",
  default_timezone: "Asia/Kolkata",
  default_currency: "INR",
  report_footer_branding: "Generated by Narrative. This report is based on Meta Ads data available at send time.",
  show_narrative_branding: true,
  include_agency_name_in_footer: true,
  include_generated_timestamp: true,
  include_data_disclaimer: true,
  report_email_tone: "internal",
};

const defaultReportSettings = {
  default_frequency: "daily",
  daily_send_time: "09:00",
  weekly_day: 1,
  weekly_time: "09:00",
  monthly_date: 1,
  monthly_time: "09:00",
  timezone: "Asia/Kolkata",
  comparison_window: "previous_completed_day",
  recipients: "",
  default_campaign_objective: "Leads",
  default_kpi: "Cost per result",
  sensitivity: "balanced",
};

const defaultNotifications = {
  email_report_delivery: true,
  critical_alerts: true,
  token_expiry_alerts: true,
  failed_report_alerts: true,
  weekly_summary: false,
  manual_send_confirmation: true,
  notify_before_meta_expiry: 7,
};

const defaultTeam = {
  members: [],
  invites: [],
  current_user_role: "member",
};

const normalizeSection = (value) =>
  sections.some((section) => section.id === value) ? value : "profile";

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const titleCase = (value = "") =>
  String(value || "unknown")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());

const initials = (value = "") =>
  value
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase() || "N";

const slugify = (value = "") =>
  value
    .toString()
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "workspace";

const parseEmails = (value = "") =>
  String(value || "")
    .split(/[,;\n]/)
    .map((email) => email.trim().toLowerCase())
    .filter(Boolean);

const invalidEmails = (emails = []) => emails.filter((email) => !EMAIL_PATTERN.test(email));

const formatDateTime = (value) => {
  if (!value) return "Not synced";

  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
};

const metaStatusLabel = (status = "unknown") => metaStatusLabels[status] || titleCase(status);

const metaStatusTone = (status = "unknown") => {
  if (status === "active") return "active";
  if (status === "expiring_soon") return "expiring_soon";
  if (status === "permission_error") return "permission_error";
  if (status === "expired") return "expired";
  if (status === "revoked") return "critical";
  return "unknown";
};

const metaStatusNeedsAttention = (status = "unknown") =>
  ["expiring_soon", "expired", "permission_error", "revoked", "unknown"].includes(status);

const tokenSummary = (connection = {}) => {
  const expiresAt = connection.token_expires_at;
  const days = connection.token_expires_in_days;

  if (!expiresAt || days === null || days === undefined) return "Token expiry unknown";
  if (days < 0) return `Expired ${Math.abs(days)} day${Math.abs(days) === 1 ? "" : "s"} ago`;
  if (days === 0) return "Expires today";
  return `Expires in ${days} day${days === 1 ? "" : "s"}`;
};

const accountAttentionCopy = (reason) => {
  if (reason === "inaccessible") return "This account is no longer accessible through the connected Meta identity.";
  if (reason === "unassigned") return "Assign this ad account to a client before creating reports.";
  if (reason === "connection_issue") return "Reports may fail until the Meta connection is restored.";
  if (reason === "removed") return "This ad account was removed from the workspace.";
  return "Review this account before using it in reports.";
};

const toApiUrl = (path) => {
  if (!path) return API_BASE;
  if (/^https?:\/\//i.test(path)) return path;
  return `${API_BASE}${path.startsWith("/") ? path : `/${path}`}`;
};

const readImageFile = (file) =>
  new Promise((resolve, reject) => {
    if (!file) {
      resolve("");
      return;
    }

    if (!file.type.startsWith("image/")) {
      reject(new Error("Please choose an image file."));
      return;
    }

    if (file.size > 2 * 1024 * 1024) {
      reject(new Error("Image must be under 2MB."));
      return;
    }

    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = () => reject(new Error("Could not read image file."));
    reader.readAsDataURL(file);
  });

function Badge({ children, tone = "revoked" }) {
  return (
    <span
      className={`inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium ${
        badgeStyles[tone] || "border-slate-200 bg-slate-50 text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300"
      }`}
    >
      {children}
    </span>
  );
}

function Card({ title, action, footer, children }) {
  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[var(--shadow-card)] dark:border-slate-800 dark:bg-slate-900/80">
      <div className="flex min-h-12 items-center justify-between gap-3 border-b border-slate-100 px-5 py-3 dark:border-slate-800">
        <h2 className="text-sm font-semibold text-slate-950 dark:text-slate-50">{title}</h2>
        {action}
      </div>
      <div className="px-5 py-5">{children}</div>
      {footer && (
        <div className="border-t border-slate-100 bg-slate-50 px-5 py-3 text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-400">
          {footer}
        </div>
      )}
    </section>
  );
}

function Field({ label, children }) {
  return (
    <label className="block">
      <span className="mb-1.5 block text-xs font-medium text-slate-600 dark:text-slate-400">{label}</span>
      {children}
    </label>
  );
}

function Input(props) {
  return (
    <input
      {...props}
      className={`h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-400 disabled:bg-slate-50 disabled:text-slate-500 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-100 dark:placeholder:text-slate-500 dark:focus:border-slate-700 dark:disabled:bg-slate-900 dark:disabled:text-slate-500 ${
        props.className || ""
      }`}
    />
  );
}

function Select(props) {
  return (
    <select
      {...props}
      className={`h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-slate-400 disabled:bg-slate-50 disabled:text-slate-500 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-100 dark:focus:border-slate-700 dark:disabled:bg-slate-900 dark:disabled:text-slate-500 ${
        props.className || ""
      }`}
    />
  );
}

function TextArea(props) {
  return (
    <textarea
      {...props}
      className={`min-h-20 w-full resize-none rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-400 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-100 dark:placeholder:text-slate-500 dark:focus:border-slate-700 ${
        props.className || ""
      }`}
    />
  );
}

function Button({ children, icon: Icon, busy, variant = "secondary", className = "", ...props }) {
  const variants = {
    primary: "border-slate-900 bg-slate-900 text-white hover:bg-slate-800 disabled:border-slate-300 disabled:bg-slate-300 dark:border-slate-100 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white",
    secondary: "border-slate-200 bg-white text-slate-700 hover:bg-slate-50 hover:border-slate-300 disabled:opacity-50 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200 dark:hover:border-slate-700 dark:hover:bg-slate-800",
    danger: "border-rose-200 bg-white text-rose-700 hover:bg-rose-50 disabled:opacity-50 dark:border-rose-900/70 dark:bg-slate-900 dark:text-rose-300 dark:hover:bg-rose-950/40",
    muted: "border-slate-200 bg-slate-100 text-slate-500 dark:border-slate-800 dark:bg-slate-800 dark:text-slate-400",
  };

  return (
    <button
      {...props}
      disabled={busy || props.disabled}
      className={`inline-flex h-9 items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium transition disabled:cursor-not-allowed ${
        variants[variant]
      } ${className}`}
    >
      {busy ? <RefreshCw size={15} className="animate-spin" /> : Icon ? <Icon size={15} /> : null}
      {children}
    </button>
  );
}

function ToggleRow({ label, description, checked, onChange }) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className="flex w-full items-center justify-between gap-4 border-b border-slate-100 py-3 text-left last:border-b-0 dark:border-slate-800"
    >
      <span>
        <span className="block text-sm font-medium text-slate-900 dark:text-slate-100">{label}</span>
        {description && <span className="mt-0.5 block text-xs text-slate-500 dark:text-slate-400">{description}</span>}
      </span>
      <span
        className={`relative h-5 w-9 rounded-full transition ${
          checked ? "bg-slate-900 dark:bg-slate-100" : "bg-slate-200 dark:bg-slate-700"
        }`}
      >
        <span
          className={`absolute top-1 h-3 w-3 rounded-full bg-white transition dark:bg-slate-950 ${checked ? "left-5" : "left-1"}`}
        />
      </span>
    </button>
  );
}

function Notice({ type, children }) {
  const styles =
    type === "error"
      ? "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900/70 dark:bg-amber-950/40 dark:text-amber-200"
      : "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900/70 dark:bg-emerald-950/40 dark:text-emerald-200";
  const Icon = type === "error" ? AlertTriangle : CheckCircle2;

  return (
    <div className={`mb-4 flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-medium ${styles}`}>
      <Icon size={15} />
      {children}
    </div>
  );
}

function IntegrationAvatar({ label }) {
  return (
    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-blue-600 text-xs font-semibold text-white">
      {initials(label || "Meta").slice(0, 1)}
    </div>
  );
}

export default function Settings() {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const { user } = useSelector((state) => state.user);
  const [activeSection, setActiveSection] = useState(() => normalizeSection(searchParams.get("tab")));
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState("");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [clients, setClients] = useState([]);
  const [metaOverview, setMetaOverview] = useState(defaultMetaOverview);
  const [metaConnections, setMetaConnections] = useState([]);
  const [adAccounts, setAdAccounts] = useState([]);
  const [assignments, setAssignments] = useState({});
  const [billing, setBilling] = useState(null);
  const [security, setSecurity] = useState(null);
  const [team, setTeam] = useState(defaultTeam);
  const [showInviteModal, setShowInviteModal] = useState(false);
  const [inviteEmail, setInviteEmail] = useState("");
  const [profileForm, setProfileForm] = useState(defaultProfile);
  const [workspaceForm, setWorkspaceForm] = useState(defaultWorkspace);
  const [reportForm, setReportForm] = useState(defaultReportSettings);
  const [notificationsForm, setNotificationsForm] = useState(defaultNotifications);
  const [passwordForm, setPasswordForm] = useState({ currentPassword: "", newPassword: "" });
  const [testRecipient, setTestRecipient] = useState("");
  const isOwner = team.current_user_role === "owner" || user?.role === "owner";

  const activeConnections = useMemo(
    () => metaConnections.filter((connection) => connection.is_active),
    [metaConnections],
  );

  const sectionTitle = sections.find((section) => section.id === activeSection)?.label || "Settings";

  const setSection = (sectionId) => {
    setActiveSection(sectionId);
    setSearchParams({ tab: sectionId });
  };

  const hydrateAdAccounts = (accounts = []) => {
    setAdAccounts(accounts);
    setAssignments(
      Object.fromEntries(accounts.map((account) => [account.id, account.assigned_client?.id || ""])),
    );
  };

  const loadSettings = async () => {
    setLoading(true);
    setError("");

    const results = await Promise.allSettled([
      api.get("/settings/profile"),
      api.get("/settings/workspace"),
      api.get("/settings/meta/overview"),
      api.get("/settings/meta/connections"),
      api.get("/settings/meta/ad-accounts"),
      api.get("/settings/report-defaults"),
      api.get("/settings/notifications"),
      api.get("/settings/billing"),
      api.get("/settings/security"),
      api.get("/settings/team"),
      api.get("/clients"),
    ]);

    const [
      profileRes,
      workspaceRes,
      overviewRes,
      connectionsRes,
      adAccountsRes,
      reportRes,
      notificationsRes,
      billingRes,
      securityRes,
      teamRes,
      clientsRes,
    ] = results;

    if (profileRes.status === "fulfilled") {
      const profile = profileRes.value.data.profile || {};
      setProfileForm({
        ...defaultProfile,
        ...profile,
        full_name: profile.full_name || profile.fullName || "",
        avatar_url: profile.avatar_url || profile.avatar || "",
      });
    }

    if (workspaceRes.status === "fulfilled") {
      setWorkspaceForm((current) => ({
        ...current,
        ...(workspaceRes.value.data.workspace || {}),
      }));
    }

    if (overviewRes.status === "fulfilled") {
      setMetaOverview({
        ...defaultMetaOverview,
        ...(overviewRes.value.data.overview || {}),
      });
    }

    if (connectionsRes.status === "fulfilled") {
      setMetaConnections(connectionsRes.value.data.connections || []);
    }

    if (adAccountsRes.status === "fulfilled") {
      hydrateAdAccounts(adAccountsRes.value.data.ad_accounts || []);
    }

    if (reportRes.status === "fulfilled") {
      const defaults = reportRes.value.data.defaults || {};
      setReportForm((current) => ({
        ...current,
        ...defaults,
        recipients: (defaults.recipients || []).join(", "),
      }));
    }

    if (notificationsRes.status === "fulfilled") {
      setNotificationsForm((current) => ({
        ...current,
        ...(notificationsRes.value.data.notifications || {}),
      }));
    }

    if (billingRes.status === "fulfilled") {
      setBilling(billingRes.value.data.billing);
    }

    if (securityRes.status === "fulfilled") {
      setSecurity(securityRes.value.data.security);
    }

    if (teamRes.status === "fulfilled") {
      setTeam({
        ...defaultTeam,
        current_user_role: teamRes.value.data.current_user_role || "member",
        members: teamRes.value.data.members || [],
        invites: teamRes.value.data.invites || [],
      });
    }

    if (clientsRes.status === "fulfilled") {
      setClients(clientsRes.value.data.clients || []);
    }

    if (results.some((result) => result.status === "rejected")) {
      setError("Some settings could not be loaded.");
    }

    setLoading(false);
  };

  const reloadMeta = async () => {
    const [overviewRes, connectionsRes, adAccountsRes, securityRes, billingRes] = await Promise.all([
      api.get("/settings/meta/overview"),
      api.get("/settings/meta/connections"),
      api.get("/settings/meta/ad-accounts"),
      api.get("/settings/security"),
      api.get("/settings/billing"),
    ]);

    setMetaOverview({
      ...defaultMetaOverview,
      ...(overviewRes.data.overview || {}),
    });
    setMetaConnections(connectionsRes.data.connections || []);
    hydrateAdAccounts(adAccountsRes.data.ad_accounts || []);
    setSecurity(securityRes.data.security);
    setBilling(billingRes.data.billing);
  };

  const reloadTeam = async () => {
    const res = await api.get("/settings/team");
    setTeam({
      ...defaultTeam,
      current_user_role: res.data.current_user_role || "member",
      members: res.data.members || [],
      invites: res.data.invites || [],
    });
  };

  useEffect(() => {
    loadSettings();
  }, []);

  useEffect(() => {
    setActiveSection(normalizeSection(searchParams.get("tab")));

    const metaStatus = searchParams.get("meta");
    if (metaStatus === "connected") setNotice("Meta connected and synced.");
    if (metaStatus === "connected-sync-failed") setNotice("Meta connected. Sync needs another try.");
    if (metaStatus === "failed") setError("Meta connection failed.");
  }, [searchParams]);

  const applyProfileResponse = (profile = {}) => {
    setProfileForm((current) => ({
      ...current,
      ...profile,
      full_name: profile.full_name || profile.fullName || current.full_name,
      avatar_url: profile.avatar_url || profile.avatar || "",
    }));
    dispatch(authSuccess({
      ...(user || {}),
      fullName: profile.fullName || profile.full_name || user?.fullName,
      email: profile.email || user?.email,
      avatar: profile.avatar_url || profile.avatar || null,
      avatar_url: profile.avatar_url || profile.avatar || null,
    }));
  };

  const applyWorkspaceResponse = (workspace = {}) => {
    setWorkspaceForm((current) => ({ ...current, ...workspace }));
    dispatch(
      authSuccess({
        ...(user || {}),
        agency: {
          ...(user?.agency || {}),
          id: workspace.id || user?.agency?.id,
          name: workspace.name,
          slug: workspace.slug,
          logo_url: workspace.logo_url || null,
          logoUrl: workspace.logo_url || null,
        },
        agencyId: workspace.id || user?.agencyId,
      }),
    );
  };

  const applyEmailSettingsResponse = (settings = {}) => {
    setWorkspaceForm((current) => ({
      ...current,
      default_sender_name: settings.senderName ?? current.default_sender_name,
      reply_to_email: settings.replyToEmail ?? current.reply_to_email,
      from_email: settings.fromEmail ?? current.from_email,
      custom_domain_status: settings.customDomainStatus ?? current.custom_domain_status,
      report_footer_branding: settings.reportFooter ?? current.report_footer_branding,
      show_narrative_branding: settings.showNarrativeBranding ?? current.show_narrative_branding,
      include_agency_name_in_footer:
        settings.includeAgencyNameInFooter ?? current.include_agency_name_in_footer,
      include_generated_timestamp:
        settings.includeGeneratedTimestamp ?? current.include_generated_timestamp,
      include_data_disclaimer: settings.includeDataDisclaimer ?? current.include_data_disclaimer,
      report_email_tone: settings.reportEmailTone ?? current.report_email_tone,
    }));
    setReportForm((current) => ({
      ...current,
      recipients: (settings.defaultRecipients || []).join(", "),
    }));
  };

  const saveProfile = async () => {
    setSaving("profile");
    setNotice("");
    setError("");

    try {
      const res = await api.patch("/settings/profile", profileForm);
      applyProfileResponse(res.data.profile);
      setNotice("Profile saved.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not save profile.");
    } finally {
      setSaving("");
    }
  };

  const saveWorkspace = async () => {
    setSaving("workspace");
    setNotice("");
    setError("");

    try {
      const payload = isOwner
        ? workspaceForm
        : (({ logo_url, ...rest }) => rest)(workspaceForm);
      const res = await api.patch("/settings/workspace", payload);
      applyWorkspaceResponse(res.data.workspace || {});
      setNotice("Workspace saved.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not save workspace.");
    } finally {
      setSaving("");
    }
  };

  const saveEmailSettings = async () => {
    setSaving("email-settings");
    setNotice("");
    setError("");

    try {
      const recipients = parseEmails(reportForm.recipients);
      const badRecipients = invalidEmails(recipients);
      const replyTo = String(workspaceForm.reply_to_email || "").trim();

      if (!String(workspaceForm.default_sender_name || "").trim()) {
        setError("Sender name is required.");
        return;
      }

      if (replyTo && !EMAIL_PATTERN.test(replyTo.toLowerCase())) {
        setError("Reply-to email is invalid.");
        return;
      }

      if (badRecipients.length) {
        setError(`Invalid recipient email: ${badRecipients[0]}`);
        return;
      }

      const res = await api.patch("/settings/email", {
        senderName: workspaceForm.default_sender_name,
        replyToEmail: replyTo,
        defaultRecipients: recipients,
        reportFooter: workspaceForm.report_footer_branding,
        showNarrativeBranding: workspaceForm.show_narrative_branding,
        includeAgencyNameInFooter: workspaceForm.include_agency_name_in_footer,
        includeGeneratedTimestamp: workspaceForm.include_generated_timestamp,
        includeDataDisclaimer: workspaceForm.include_data_disclaimer,
        reportEmailTone: workspaceForm.report_email_tone,
      });

      applyEmailSettingsResponse(res.data.email_settings || {});
      setNotice("Email settings saved.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not save email settings.");
    } finally {
      setSaving("");
    }
  };

  const sendTestEmail = async () => {
    const recipient = String(testRecipient || "").trim().toLowerCase();
    const replyTo = String(workspaceForm.reply_to_email || "").trim().toLowerCase();

    setSaving("test-email");
    setNotice("");
    setError("");

    try {
      if (!EMAIL_PATTERN.test(recipient)) {
        setError("Enter a valid test recipient email.");
        return;
      }

      if (replyTo && !EMAIL_PATTERN.test(replyTo)) {
        setError("Reply-to email is invalid.");
        return;
      }

      const res = await api.post("/settings/email/test", {
        testRecipient: recipient,
        senderName: workspaceForm.default_sender_name,
        replyToEmail: replyTo,
        reportFooter: workspaceForm.report_footer_branding,
        showNarrativeBranding: workspaceForm.show_narrative_branding,
        includeAgencyNameInFooter: workspaceForm.include_agency_name_in_footer,
        includeGeneratedTimestamp: workspaceForm.include_generated_timestamp,
        includeDataDisclaimer: workspaceForm.include_data_disclaimer,
        reportEmailTone: workspaceForm.report_email_tone,
      });

      setNotice(res.data.message || "Test email sent.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not send test email.");
    } finally {
      setSaving("");
    }
  };

  const saveNotifications = async () => {
    setSaving("notifications");
    setNotice("");
    setError("");

    try {
      const res = await api.patch("/settings/notifications", {
        ...notificationsForm,
        notify_before_meta_expiry: Number(notificationsForm.notify_before_meta_expiry),
      });
      setNotificationsForm((current) => ({ ...current, ...(res.data.notifications || {}) }));
      setNotice("Notifications saved.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not save notifications.");
    } finally {
      setSaving("");
    }
  };

  const changePassword = async () => {
    setSaving("security");
    setNotice("");
    setError("");

    try {
      await api.post("/settings/security/change-password", passwordForm);
      setPasswordForm({ currentPassword: "", newPassword: "" });
      setNotice("Password updated.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not update password.");
    } finally {
      setSaving("");
    }
  };

  const saveActiveSection = () => {
    if (activeSection === "workspace") return saveWorkspace();
    if (activeSection === "profile") return saveProfile();
    if (activeSection === "report-defaults") return saveEmailSettings();
    if (activeSection === "notifications") return saveNotifications();
    if (activeSection === "security" && passwordForm.newPassword) return changePassword();
    return null;
  };

  const sendInvite = async (event) => {
    event.preventDefault();
    const email = inviteEmail.trim().toLowerCase();
    setSaving("team-invite");
    setNotice("");
    setError("");

    try {
      if (!EMAIL_PATTERN.test(email)) {
        setError("Enter a valid invite email.");
        return;
      }

      const res = await api.post("/settings/team/invites", { email });
      await reloadTeam();
      setInviteEmail("");
      setShowInviteModal(false);
      setNotice(res.data.message || "Invitation sent.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not send invitation.");
    } finally {
      setSaving("");
    }
  };

  const resendInvite = async (invite) => {
    setSaving(`resend-invite-${invite.id}`);
    setNotice("");
    setError("");

    try {
      const res = await api.post(`/settings/team/invites/${invite.id}/resend`);
      await reloadTeam();
      setNotice(res.data.message || "Invitation resent.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not resend invitation.");
    } finally {
      setSaving("");
    }
  };

  const revokeInvite = async (invite) => {
    if (!window.confirm(`Revoke invitation for ${invite.email}?`)) return;

    setSaving(`revoke-invite-${invite.id}`);
    setNotice("");
    setError("");

    try {
      const res = await api.post(`/settings/team/invites/${invite.id}/revoke`);
      await reloadTeam();
      setNotice(res.data.message || "Invitation revoked.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not revoke invitation.");
    } finally {
      setSaving("");
    }
  };

  const removeMember = async (member) => {
    const message = [
      "Remove this member from the workspace?",
      "",
      "They will lose access to clients, reports, Meta connections, and activity in this workspace.",
    ].join("\n");

    if (!window.confirm(message)) return;

    setSaving(`remove-member-${member.id}`);
    setNotice("");
    setError("");

    try {
      const res = await api.delete(`/settings/team/members/${member.id}`);
      await Promise.all([reloadTeam(), reloadMeta().catch(() => null)]);
      setNotice(res.data.message || "Member removed.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not remove member.");
    } finally {
      setSaving("");
    }
  };

  const canSave = ((activeSection === "workspace" && isOwner) ||
    ["profile", "report-defaults", "notifications"].includes(activeSection))
    || (activeSection === "security" && Boolean(passwordForm.newPassword));

  const connectMeta = () => {
    window.location.href = toApiUrl("/settings/meta/connect/start");
  };

  const syncAllMeta = async () => {
    setSaving("sync-all");
    setNotice("");
    setError("");

    try {
      const res = await api.post("/settings/meta/sync-all");
      await reloadMeta();
      if (res.data.success === false) {
        setError(res.data.message || "Meta synced with connection issues.");
      } else {
        setNotice(res.data.message || "Meta ad accounts synced.");
      }
    } catch (err) {
      setError(err.response?.data?.message || "Could not sync Meta ad accounts.");
    } finally {
      setSaving("");
    }
  };

  const reconnectConnection = async (connection) => {
    setSaving(`reconnect-${connection.id}`);
    setNotice("");
    setError("");

    try {
      const res = await api.post(`/settings/meta/connections/${connection.id}/reconnect`);
      window.location.href = toApiUrl(res.data.redirect_url);
    } catch (err) {
      setError(err.response?.data?.message || "Could not start Meta reconnect.");
      setSaving("");
    }
  };

  const syncConnection = async (connectionId) => {
    setSaving(`sync-${connectionId}`);
    setNotice("");
    setError("");

    try {
      const res = await api.post(`/settings/meta/connections/${connectionId}/sync`);
      await reloadMeta();
      setNotice(res.data.message || "Meta synced.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not sync Meta.");
    } finally {
      setSaving("");
    }
  };

  const removeConnection = async (connection) => {
    const profileName = connection.meta_user_name || "this Meta connection";
    const adAccountCount = connection.ad_accounts_count || 0;
    const reportCount = connection.affected_reports_count || connection.reports_count || 0;
    const message = [
      `Disconnect ${profileName}?`,
      "",
      `This connection is linked to ${adAccountCount} ad account${adAccountCount === 1 ? "" : "s"}.`,
      `${reportCount} active report${reportCount === 1 ? "" : "s"} may fail until access is restored.`,
      "",
      "Reports will not be deleted, but linked Meta access will be disabled.",
    ].join("\n");

    if (!window.confirm(message)) return;

    setSaving(`remove-${connection.id}`);
    setNotice("");
    setError("");

    try {
      await api.delete(`/settings/meta/connections/${connection.id}`);
      await reloadMeta();
      setNotice("Meta connection disconnected.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not remove connection.");
    } finally {
      setSaving("");
    }
  };

  const assignAdAccount = async (accountId) => {
    setSaving(`assign-${accountId}`);
    setNotice("");
    setError("");

    try {
      const account = adAccounts.find((item) => item.id === accountId);
      const nextClientId = assignments[accountId] || null;
      const currentClientId = account?.assigned_client?.id || null;
      const clientAlreadyAssignedAccount = nextClientId
        ? adAccounts.find(
            (item) => item.id !== accountId && item.assigned_client?.id === nextClientId
          )
        : null;
      const requiresConfirmation =
        Boolean(currentClientId && currentClientId !== nextClientId) ||
        Boolean(clientAlreadyAssignedAccount);

      if (
        requiresConfirmation &&
        !window.confirm(
          "Change Meta ad account?\n\nNew reports for this client will use the newly assigned account. Existing reports will remain linked to the Meta ad account they were created with."
        )
      ) {
        setSaving("");
        return;
      }

      await api.patch(`/settings/meta/ad-accounts/${accountId}/assign-client`, {
        clientId: nextClientId,
        confirmReassignment: requiresConfirmation,
      });
      await reloadMeta();
      setNotice("Ad account assignment saved.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not assign account.");
    } finally {
      setSaving("");
    }
  };

  const refreshCampaigns = async (account) => {
    setSaving(`campaigns-${account.id}`);
    setNotice("");
    setError("");

    try {
      const res = await api.post(`/settings/meta/ad-accounts/${account.id}/refresh-campaigns`);
      await reloadMeta();
      setNotice(`${res.data.campaign_count || 0} campaigns refreshed.`);
    } catch (err) {
      setError(err.response?.data?.message || "Could not refresh campaigns.");
    } finally {
      setSaving("");
    }
  };

  const removeAdAccount = async (account) => {
    const reportCount = account.active_reports_using_account || account.reports_using_account || 0;
    const message = [
      `Remove ${account.name || account.ad_account_id}?`,
      "",
      `This account is used by ${reportCount} active report${reportCount === 1 ? "" : "s"}.`,
      "Removing it may pause or break scheduled reports that depend on this account.",
      "",
      "Reports will not be deleted.",
    ].join("\n");

    if (!window.confirm(message)) return;

    setSaving(`remove-account-${account.id}`);
    setNotice("");
    setError("");

    try {
      await api.delete(`/settings/meta/ad-accounts/${account.id}`);
      await reloadMeta();
      setNotice("Ad account removed.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not remove ad account.");
    } finally {
      setSaving("");
    }
  };

  const uploadProfileAvatar = async (event) => {
    try {
      const image = await readImageFile(event.target.files?.[0]);
      setSaving("profile-avatar");
      const res = await api.patch("/settings/profile", {
        ...profileForm,
        avatar_url: image,
      });
      applyProfileResponse(res.data.profile);
      setNotice("Profile picture updated.");
      setError("");
    } catch (err) {
      setError(err.response?.data?.message || err.message || "Could not update profile picture.");
    } finally {
      setSaving("");
      event.target.value = "";
    }
  };

  const uploadWorkspaceLogo = async (event) => {
    if (!isOwner) return;

    try {
      const image = await readImageFile(event.target.files?.[0]);
      setSaving("workspace-logo");
      const res = await api.patch("/settings/workspace", {
        ...workspaceForm,
        logo_url: image,
      });
      applyWorkspaceResponse(res.data.workspace);
      setNotice("Workspace logo updated.");
      setError("");
    } catch (err) {
      setError(err.response?.data?.message || err.message || "Could not update workspace logo.");
    } finally {
      setSaving("");
      event.target.value = "";
    }
  };

  const removeProfileAvatar = async () => {
    setSaving("profile-avatar");
    setNotice("");
    setError("");

    try {
      const res = await api.patch("/settings/profile", {
        ...profileForm,
        avatar_url: "",
      });
      applyProfileResponse(res.data.profile);
      setNotice("Profile picture removed.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not remove profile picture.");
    } finally {
      setSaving("");
    }
  };

  const removeWorkspaceLogo = async () => {
    if (!isOwner) return;

    setSaving("workspace-logo");
    setNotice("");
    setError("");

    try {
      const res = await api.patch("/settings/workspace", {
        ...workspaceForm,
        logo_url: "",
      });
      applyWorkspaceResponse(res.data.workspace);
      setNotice("Workspace logo removed.");
    } catch (err) {
      setError(err.response?.data?.message || "Could not remove workspace logo.");
    } finally {
      setSaving("");
    }
  };

  const renderWorkspace = () => (
    <Card title="Workspace" footer={workspaceForm.updatedAt ? `Last updated ${formatDateTime(workspaceForm.updatedAt)}` : "Workspace settings are saved for the agency."}>
      <div className="space-y-4">
        <div className="flex items-center gap-4 rounded-md border border-slate-200 bg-slate-50 p-4">
          {workspaceForm.logo_url ? (
            <img
              src={workspaceForm.logo_url}
              alt={workspaceForm.name || "Workspace logo"}
              className="h-14 w-14 rounded-full object-cover ring-1 ring-slate-200"
            />
          ) : (
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-900 text-sm font-semibold text-white">
              {initials(workspaceForm.name)}
            </div>
          )}
          <div className="min-w-0 flex-1">
            <div className="text-sm font-medium text-slate-900">Workspace logo</div>
            <div className="mt-1 text-xs text-slate-500">
              {isOwner ? "Owners can upload or remove the agency logo." : "Only the workspace owner can change the logo."}
            </div>
          </div>
          {isOwner && (
            <div className="flex flex-wrap gap-2">
              <input
                id="workspace-logo-upload"
                type="file"
                accept="image/*"
                className="hidden"
                onChange={uploadWorkspaceLogo}
              />
              <Button
                icon={Upload}
                busy={saving === "workspace-logo"}
                onClick={() => document.getElementById("workspace-logo-upload")?.click()}
              >
                Upload
              </Button>
              <Button
                variant="danger"
                icon={Trash2}
                busy={saving === "workspace-logo"}
                disabled={!workspaceForm.logo_url}
                onClick={removeWorkspaceLogo}
              >
                Remove
              </Button>
            </div>
          )}
        </div>
        <Field label="Agency Name">
          <Input
            value={workspaceForm.name}
            disabled={!isOwner}
            onChange={(event) => setWorkspaceForm((current) => ({ ...current, name: event.target.value }))}
            placeholder="Apex Media Group"
          />
        </Field>
        <Field label="Timezone">
          <Select
            value={workspaceForm.default_timezone}
            disabled={!isOwner}
            onChange={(event) =>
              setWorkspaceForm((current) => ({ ...current, default_timezone: event.target.value }))
            }
          >
            {timezones.map((timezone) => (
              <option key={timezone} value={timezone}>{timezone}</option>
            ))}
          </Select>
        </Field>
        <Field label="Default Currency">
          <Select
            value={workspaceForm.default_currency}
            disabled={!isOwner}
            onChange={(event) =>
              setWorkspaceForm((current) => ({ ...current, default_currency: event.target.value }))
            }
          >
            {currencies.map((currency) => (
              <option key={currency} value={currency}>{currency}</option>
            ))}
          </Select>
        </Field>
        <Field label="Workspace Slug">
          <div className="flex h-9 items-center rounded-md border border-slate-200 bg-white text-sm">
            <span className="border-r border-slate-100 px-3 text-slate-400">narrative.app</span>
            <span className="px-3 text-slate-900">{slugify(workspaceForm.name)}</span>
          </div>
        </Field>
      </div>
    </Card>
  );

  const renderMeta = () => {
    const overviewItems = [
      ["Meta connections", metaOverview.connectedProfilesCount],
      ["Synced ad accounts", metaOverview.syncedAdAccountsCount],
      ["Accounts needing attention", metaOverview.needsAttentionCount],
      ["Affected reports", metaOverview.affectedReportsCount],
    ];

    return (
      <div className="space-y-5">
        <Card
          title="Meta Integration"
          action={
            <div className="flex flex-wrap gap-2">
              {!activeConnections.length && (
                <Button variant="primary" icon={Link2} onClick={connectMeta}>
                  Connect Meta Account
                </Button>
              )}
              <Button
                icon={RefreshCw}
                disabled={!activeConnections.length}
                busy={saving === "sync-all"}
                onClick={syncAllMeta}
              >
                Sync Ad Accounts
              </Button>
            </div>
          }
          footer="Narrative uses read-only Meta access for reporting. It does not modify campaigns."
        >
          <div className="space-y-5">
            <div>
              <p className="text-sm text-slate-600">
                Connect Meta once, sync accessible ad accounts, and assign them to clients.
              </p>
            </div>

            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {overviewItems.map(([label, value]) => (
                <div key={label} className="rounded-md border border-slate-200 bg-slate-50 p-3">
                  <div className="text-xs font-medium text-slate-500">{label}</div>
                  <div className="mt-1 text-2xl font-semibold text-slate-950">{value || 0}</div>
                </div>
              ))}
            </div>

            {!activeConnections.length ? (
              <div className="rounded-md border border-dashed border-slate-200 bg-slate-50 px-4 py-8 text-center">
                <Plug size={22} className="mx-auto text-slate-400" />
                <div className="mt-3 text-sm font-semibold text-slate-950">No Meta account connected</div>
                <div className="mx-auto mt-1 max-w-md text-sm text-slate-500">
                  Connect Meta to sync ad accounts and create automated campaign reports.
                </div>
                <Button variant="primary" icon={Link2} className="mt-4" onClick={connectMeta}>
                  Connect Meta Account
                </Button>
              </div>
            ) : (
              <div className="rounded-md border border-sky-100 bg-sky-50 px-3 py-2 text-sm text-sky-800">
                If an ad account is missing, get access in Meta Business Manager and sync the workspace connection again.
              </div>
            )}
          </div>
        </Card>

        <Card title="Connected Meta Profile">
          {metaConnections.length ? (
            <div className="space-y-3">
              {metaConnections.map((connection) => {
                const status = connection.status || "unknown";
                const hasIssue = metaStatusNeedsAttention(status);

                return (
                  <div key={connection.id} className="rounded-md border border-slate-200 bg-white p-4">
                    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                      <div className="flex min-w-0 gap-3">
                        <IntegrationAvatar label={connection.meta_user_name} />
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <div className="truncate text-sm font-semibold text-slate-950">
                              {connection.meta_user_name || "Meta profile"}
                            </div>
                            <Badge tone={metaStatusTone(status)}>{metaStatusLabel(status)}</Badge>
                          </div>
                          <div className="mt-1 truncate text-xs text-slate-500">
                            {connection.meta_user_id
                              ? `Meta user ID: ${connection.meta_user_id}`
                              : connection.ad_account_id
                                ? `Ad account: ${connection.ad_account_id}`
                                : "Meta identity unknown"}
                          </div>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2">
                        <Button
                          icon={Link2}
                          busy={saving === `reconnect-${connection.id}`}
                          onClick={() => reconnectConnection(connection)}
                        >
                          Reconnect
                        </Button>
                        <Button
                          icon={RefreshCw}
                          busy={saving === `sync-${connection.id}`}
                          disabled={!connection.is_active}
                          onClick={() => syncConnection(connection.id)}
                        >
                          Sync ad accounts
                        </Button>
                        <Button
                          variant="danger"
                          icon={Trash2}
                          busy={saving === `remove-${connection.id}`}
                          onClick={() => removeConnection(connection)}
                        >
                          Disconnect
                        </Button>
                      </div>
                    </div>

                    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                      <div className="rounded-md bg-slate-50 p-3">
                        <div className="text-xs font-medium text-slate-500">Token</div>
                        <div className="mt-1 text-sm font-medium text-slate-900">{tokenSummary(connection)}</div>
                        <div className="mt-0.5 text-xs text-slate-500">
                          {connection.token_expires_at ? formatDateTime(connection.token_expires_at) : "Expiry date unknown"}
                        </div>
                      </div>
                      <div className="rounded-md bg-slate-50 p-3">
                        <div className="text-xs font-medium text-slate-500">Connected by</div>
                        <div className="mt-1 truncate text-sm font-medium text-slate-900">
                          {connection.connected_by?.email || connection.connected_by?.name || "Unknown user"}
                        </div>
                      </div>
                      <div className="rounded-md bg-slate-50 p-3">
                        <div className="text-xs font-medium text-slate-500">Ad accounts synced</div>
                        <div className="mt-1 text-sm font-medium text-slate-900">{connection.ad_accounts_count || 0}</div>
                      </div>
                      <div className="rounded-md bg-slate-50 p-3">
                        <div className="text-xs font-medium text-slate-500">Reports affected</div>
                        <div className="mt-1 text-sm font-medium text-slate-900">{connection.affected_reports_count || 0}</div>
                      </div>
                    </div>

                    <div className="mt-3 grid gap-3 sm:grid-cols-2">
                      <div>
                        <div className="text-xs font-medium text-slate-500">Permissions</div>
                        <div className="mt-2 flex flex-wrap gap-1.5">
                          {(connection.permissions || []).length ? (
                            connection.permissions.map((permission) => (
                              <span key={permission} className="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-600">
                                {permission}
                              </span>
                            ))
                          ) : (
                            <span className="text-xs text-slate-500">Permissions not verified</span>
                          )}
                        </div>
                      </div>
                      <div>
                        <div className="text-xs font-medium text-slate-500">Last synced</div>
                        <div className="mt-2 text-sm text-slate-700">{formatDateTime(connection.last_synced_at)}</div>
                      </div>
                    </div>

                    {hasIssue && (
                      <div className="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">
                        Reports using this connection may fail until Meta access is restored.
                      </div>
                    )}

                    {connection.last_error && (
                      <div className="mt-3 rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-800">
                        {connection.last_error}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="rounded-md border border-dashed border-slate-200 bg-slate-50 px-4 py-8 text-center">
              <Plug size={20} className="mx-auto text-slate-400" />
              <div className="mt-3 text-sm font-semibold text-slate-950">No Meta profiles connected yet</div>
              <div className="mt-1 text-sm text-slate-500">Connected Meta profiles will appear here after OAuth.</div>
            </div>
          )}
        </Card>

        <Card title="Synced Ad Accounts / Account Mapping">
          {adAccounts.length ? (
            <div className="space-y-3">
              {adAccounts.map((account) => {
                const currentAssignment = account.assigned_client?.id || "";
                const selectedAssignment = assignments[account.id] || "";
                const hasChanged = selectedAssignment !== currentAssignment;
                const connectionStatus = account.connected_profile?.status || "unknown";
                const blocksCampaignRefresh = ["expired", "permission_error", "revoked", "unknown"].includes(connectionStatus);
                const activeReportCount = account.active_reports_using_account || 0;

                return (
                  <div key={account.id} className="rounded-md border border-slate-200 bg-white p-4">
                    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <div className="truncate text-sm font-semibold text-slate-950">
                            {account.name || account.ad_account_id}
                          </div>
                          <Badge tone={account.is_active ? "active" : "removed"}>
                            {account.is_active ? "Active" : "Removed"}
                          </Badge>
                          {!account.assigned_client?.id && <Badge tone="unassigned">Unassigned</Badge>}
                          {account.attention_reason === "connection_issue" && (
                            <Badge tone={metaStatusTone(connectionStatus)}>Connection issue</Badge>
                          )}
                        </div>
                        <div className="mt-1 text-xs text-slate-500">{account.ad_account_id}</div>

                        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                          <div>
                            <div className="text-xs font-medium text-slate-500">Connection</div>
                            <div className="mt-1 text-sm text-slate-800">
                              {account.connected_profile?.meta_user_name || "Unknown profile"}
                            </div>
                            <div className="mt-1">
                              <Badge tone={metaStatusTone(connectionStatus)}>{metaStatusLabel(connectionStatus)}</Badge>
                            </div>
                          </div>
                          <div>
                            <div className="text-xs font-medium text-slate-500">Currency</div>
                            <div className="mt-1 text-sm text-slate-800">{account.currency || "Unknown"}</div>
                          </div>
                          <div>
                            <div className="text-xs font-medium text-slate-500">Timezone</div>
                            <div className="mt-1 text-sm text-slate-800">{account.timezone_name || "Unknown"}</div>
                          </div>
                          <div>
                            <div className="text-xs font-medium text-slate-500">Reports</div>
                            <div className="mt-1 text-sm text-slate-800">
                              {account.reports_using_account || 0} total, {activeReportCount} active
                            </div>
                          </div>
                        </div>

                        <div className="mt-3 grid gap-3 sm:grid-cols-3">
                          <div className="rounded-md bg-slate-50 p-3">
                            <div className="text-xs font-medium text-slate-500">Meta status</div>
                            <div className="mt-1 text-sm text-slate-800">{account.account_status || "Unknown"}</div>
                          </div>
                          <div className="rounded-md bg-slate-50 p-3">
                            <div className="text-xs font-medium text-slate-500">Last synced</div>
                            <div className="mt-1 text-sm text-slate-800">{formatDateTime(account.last_synced_at)}</div>
                          </div>
                          <div className="rounded-md bg-slate-50 p-3">
                            <div className="text-xs font-medium text-slate-500">Campaigns refreshed</div>
                            <div className="mt-1 text-sm text-slate-800">{formatDateTime(account.campaigns_last_synced_at)}</div>
                          </div>
                        </div>

                        {account.needs_attention && (
                          <div className="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">
                            {activeReportCount && account.attention_reason === "connection_issue"
                              ? `${activeReportCount} reports may fail until this Meta connection is restored.`
                              : accountAttentionCopy(account.attention_reason)}
                          </div>
                        )}
                      </div>

                      <div className="space-y-3">
                        <Field label="Assigned client">
                          <Select
                            value={selectedAssignment}
                            disabled={!clients.length || !account.is_active || account.is_accessible === false}
                            onChange={(event) =>
                              setAssignments((current) => ({ ...current, [account.id]: event.target.value }))
                            }
                          >
                            <option value="">Unassigned</option>
                            {clients.map((client) => (
                              <option key={client._id} value={client._id}>{client.name}</option>
                            ))}
                          </Select>
                        </Field>
                        {!clients.length && (
                          <div className="text-xs text-slate-500">Create a client first before assigning this ad account.</div>
                        )}
                        <div className="flex flex-wrap gap-2">
                          <Button
                            disabled={!hasChanged || !clients.length || !account.is_active || account.is_accessible === false}
                            busy={saving === `assign-${account.id}`}
                            onClick={() => assignAdAccount(account.id)}
                          >
                            Save assignment
                          </Button>
                          <Button
                            icon={ExternalLink}
                            disabled={!account.assigned_client?.id}
                            onClick={() => navigate(`/clients/${account.assigned_client.id}`)}
                          >
                            Client
                          </Button>
                          <Button
                            icon={RefreshCw}
                            busy={saving === `campaigns-${account.id}`}
                            disabled={!account.is_active || account.is_accessible === false || blocksCampaignRefresh}
                            onClick={() => refreshCampaigns(account)}
                          >
                            Refresh campaigns
                          </Button>
                          <Button
                            variant="danger"
                            icon={Trash2}
                            busy={saving === `remove-account-${account.id}`}
                            onClick={() => removeAdAccount(account)}
                          >
                            Remove
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="rounded-md border border-dashed border-slate-200 bg-slate-50 px-4 py-8 text-center">
              <Plug size={20} className="mx-auto text-slate-400" />
              <div className="mt-3 text-sm font-semibold text-slate-950">No ad accounts synced yet</div>
              <div className="mx-auto mt-1 max-w-md text-sm text-slate-500">
                Connect Meta or sync accounts to see ad accounts you can assign to clients.
              </div>
              <Button
                icon={RefreshCw}
                className="mt-4"
                disabled={!activeConnections.length}
                busy={saving === "sync-all"}
                onClick={syncAllMeta}
              >
                Sync Ad Accounts
              </Button>
            </div>
          )}
        </Card>
      </div>
    );
  };

  const renderEmailSettings = () => {
    const recipients = parseEmails(reportForm.recipients);
    const badRecipients = invalidEmails(recipients);
    const footerParts = [
      workspaceForm.include_agency_name_in_footer && workspaceForm.name
        ? `Prepared for ${workspaceForm.name}.`
        : "",
      workspaceForm.report_footer_branding,
      workspaceForm.include_generated_timestamp ? "Generated Jun 15, 2026, 9:00 AM." : "",
      workspaceForm.include_data_disclaimer ? "Based on Meta Ads data available at send time." : "",
      workspaceForm.show_narrative_branding ? "Powered by Narrative." : "",
    ].filter(Boolean);
    const toneIsClientFriendly = workspaceForm.report_email_tone === "client_friendly";

    return (
      <div className="space-y-5">
        <Card title="Sender Identity">
          <div className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Sender Name">
                <Input
                  value={workspaceForm.default_sender_name}
                  onChange={(event) =>
                    setWorkspaceForm((current) => ({ ...current, default_sender_name: event.target.value }))
                  }
                  placeholder="Narrative Reports"
                />
              </Field>
              <Field label="Reply-To Email">
                <Input
                  type="email"
                  value={workspaceForm.reply_to_email || ""}
                  onChange={(event) =>
                    setWorkspaceForm((current) => ({ ...current, reply_to_email: event.target.value }))
                  }
                  placeholder="ops@agency.com"
                />
              </Field>
              <Field label="From Email">
                <Input value={workspaceForm.from_email || "reports@narrative.app"} disabled />
              </Field>
              <Field label="Custom Sending Domain">
                <div className="flex h-9 items-center justify-between rounded-md border border-slate-200 bg-slate-50 px-3 text-sm">
                  <span className="text-slate-600">{titleCase(workspaceForm.custom_domain_status || "coming_soon")}</span>
                  <Badge tone="unknown">Coming soon</Badge>
                </div>
              </Field>
            </div>
            <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-600">
              Reports are currently sent from Narrative's verified email domain. Replies can be routed to your reply-to email.
            </div>
          </div>
        </Card>

        <Card title="Default Recipients">
          <div className="space-y-3">
            <Field label="Default Recipients">
              <TextArea
                value={reportForm.recipients}
                onChange={(event) => setReportForm((current) => ({ ...current, recipients: event.target.value }))}
                placeholder="brand@client.com, ops@agency.com"
              />
            </Field>
            <div className="text-sm text-slate-500">
              These recipients are prefilled when creating new reports. You can still customize recipients per report.
            </div>
            {recipients.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {recipients.map((email) => (
                  <span
                    key={email}
                    className={`rounded-md border px-2 py-1 text-xs ${
                      badRecipients.includes(email)
                        ? "border-rose-200 bg-rose-50 text-rose-700"
                        : "border-slate-200 bg-slate-50 text-slate-600"
                    }`}
                  >
                    {email}
                  </span>
                ))}
              </div>
            )}
            {badRecipients.length > 0 && (
              <div className="rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">
                Invalid recipient email: {badRecipients[0]}
              </div>
            )}
          </div>
        </Card>

        <Card title="Email Branding">
          <div className="space-y-4">
            <Field label="Report Footer">
              <TextArea
                value={workspaceForm.report_footer_branding || ""}
                onChange={(event) =>
                  setWorkspaceForm((current) => ({ ...current, report_footer_branding: event.target.value }))
                }
                placeholder="Generated by Narrative. This report is based on Meta Ads data available at send time."
              />
            </Field>
            <div className="rounded-md border border-slate-200 bg-slate-50 p-4">
              <div className="flex items-center gap-3">
                {workspaceForm.logo_url ? (
                  <img
                    src={workspaceForm.logo_url}
                    alt={workspaceForm.name || "Workspace logo"}
                    className="h-10 w-10 rounded-full object-cover ring-1 ring-slate-200"
                  />
                ) : (
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-900 text-xs font-semibold text-white">
                    {initials(workspaceForm.name)}
                  </div>
                )}
                <div>
                  <div className="text-sm font-medium text-slate-900">Agency logo</div>
                  <div className="text-xs text-slate-500">Uses the workspace logo configured in Workspace settings.</div>
                </div>
              </div>
            </div>
            <div className="divide-y divide-slate-100 rounded-md border border-slate-200 px-4">
              <ToggleRow
                label="Show Narrative branding"
                description="Include the Narrative mark in report email footers."
                checked={workspaceForm.show_narrative_branding}
                onChange={(value) =>
                  setWorkspaceForm((current) => ({ ...current, show_narrative_branding: value }))
                }
              />
              <ToggleRow
                label="Include agency name in footer"
                description="Add the workspace name to the footer copy."
                checked={workspaceForm.include_agency_name_in_footer}
                onChange={(value) =>
                  setWorkspaceForm((current) => ({ ...current, include_agency_name_in_footer: value }))
                }
              />
              <ToggleRow
                label="Include generated timestamp"
                description="Show when the report email was generated."
                checked={workspaceForm.include_generated_timestamp}
                onChange={(value) =>
                  setWorkspaceForm((current) => ({ ...current, include_generated_timestamp: value }))
                }
              />
              <ToggleRow
                label="Include data disclaimer"
                description="Clarify that report data depends on Meta availability at send time."
                checked={workspaceForm.include_data_disclaimer}
                onChange={(value) =>
                  setWorkspaceForm((current) => ({ ...current, include_data_disclaimer: value }))
                }
              />
            </div>
          </div>
        </Card>

        <Card title="Email Style / Tone">
          <div className="grid gap-3 sm:grid-cols-2">
            {[
              ["internal", "Internal / tactical", "Direct, operational language for media teams."],
              ["client_friendly", "Client-friendly", "Softer wording for client-facing updates."],
            ].map(([value, label, description]) => {
              const selected = workspaceForm.report_email_tone === value;

              return (
                <button
                  key={value}
                  type="button"
                  onClick={() => setWorkspaceForm((current) => ({ ...current, report_email_tone: value }))}
                  className={`rounded-md border p-4 text-left transition ${
                    selected
                      ? "border-slate-900 bg-slate-50 shadow-sm"
                      : "border-slate-200 bg-white hover:bg-slate-50"
                  }`}
                >
                  <div className="flex items-center justify-between gap-3">
                    <div className="text-sm font-semibold text-slate-950">{label}</div>
                    {selected && <Badge tone="active">Selected</Badge>}
                  </div>
                  <div className="mt-1 text-sm text-slate-500">{description}</div>
                </button>
              );
            })}
          </div>
          <div className="mt-3 text-sm text-slate-500">
            Choose whether reports are written for your internal media team or for client-facing updates.
          </div>
        </Card>

        <Card title="Email Preview">
          <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
            <div className="rounded-lg border border-slate-200 bg-white shadow-sm">
              <div className="border-b border-slate-100 px-5 py-4">
                <div className="text-xs text-slate-500">
                  From {workspaceForm.default_sender_name || "Narrative Reports"} &lt;{workspaceForm.from_email || "reports@narrative.app"}&gt;
                </div>
                <div className="mt-1 text-xs text-slate-500">
                  Reply-to {workspaceForm.reply_to_email || "Not set"}
                </div>
                <div className="mt-3 text-base font-semibold text-slate-950">
                  Action needed: Refresh creative in Retargeting
                </div>
              </div>
              <div className="space-y-3 px-5 py-4">
                <div className="inline-flex rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">
                  Review today
                </div>
                <div className="text-sm leading-6 text-slate-600">
                  {toneIsClientFriendly
                    ? "Engagement softened versus the previous period. Refresh the creative angle before scaling budget."
                    : "People are seeing the ads, but fewer are engaging. Refresh the hook before adding budget."}
                </div>
                <div className="grid gap-2 sm:grid-cols-3">
                  {[
                    ["CTR", "-18.4%"],
                    ["CPC", "+12.9%"],
                    ["Spend", "INR 8,420"],
                  ].map(([label, value]) => (
                    <div key={label} className="rounded-md border border-slate-200 bg-slate-50 p-3">
                      <div className="text-xs text-slate-500">{label}</div>
                      <div className="mt-1 text-sm font-semibold text-slate-950">{value}</div>
                    </div>
                  ))}
                </div>
                <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3">
                  <div className="text-xs font-semibold text-emerald-700">Do this now</div>
                  <div className="mt-1 text-sm text-emerald-900">
                    Test a clearer offer-led visual and keep budget stable until engagement recovers.
                  </div>
                </div>
              </div>
              <div className="border-t border-slate-100 bg-slate-50 px-5 py-3 text-xs leading-5 text-slate-500">
                {footerParts.join(" ")}
              </div>
            </div>
          </div>
        </Card>

        <Card title="Test Email">
          <div className="space-y-3">
            <Field label="Test Recipient Email">
              <Input
                type="email"
                value={testRecipient}
                onChange={(event) => setTestRecipient(event.target.value)}
                placeholder="you@agency.com"
              />
            </Field>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="text-sm text-slate-500">
                Sends a compact sample report using the current settings on this page.
              </div>
              <Button
                icon={ExternalLink}
                busy={saving === "test-email"}
                onClick={sendTestEmail}
              >
                Send test email
              </Button>
            </div>
          </div>
        </Card>
      </div>
    );
  };

  const renderNotifications = () => (
    <Card title="Notifications">
      <ToggleRow
        label="Report delivery emails"
        description="Scheduled report delivery."
        checked={notificationsForm.email_report_delivery}
        onChange={(value) => setNotificationsForm((current) => ({ ...current, email_report_delivery: value }))}
      />
      <ToggleRow
        label="Critical signal alerts"
        description="Immediate action alerts."
        checked={notificationsForm.critical_alerts}
        onChange={(value) => setNotificationsForm((current) => ({ ...current, critical_alerts: value }))}
      />
      <ToggleRow
        label="Meta token expiry alerts"
        description="Connection health warnings."
        checked={notificationsForm.token_expiry_alerts}
        onChange={(value) => setNotificationsForm((current) => ({ ...current, token_expiry_alerts: value }))}
      />
      <ToggleRow
        label="Failed report alerts"
        description="Report execution failures."
        checked={notificationsForm.failed_report_alerts}
        onChange={(value) => setNotificationsForm((current) => ({ ...current, failed_report_alerts: value }))}
      />
      <ToggleRow
        label="Weekly workspace summary"
        description="A weekly operating summary."
        checked={notificationsForm.weekly_summary}
        onChange={(value) => setNotificationsForm((current) => ({ ...current, weekly_summary: value }))}
      />
      <div className="mt-4 max-w-xs">
        <Field label="Meta expiry notice days">
          <Input
            type="number"
            min="1"
            max="30"
            value={notificationsForm.notify_before_meta_expiry}
            onChange={(event) =>
              setNotificationsForm((current) => ({ ...current, notify_before_meta_expiry: event.target.value }))
            }
          />
        </Field>
      </div>
    </Card>
  );

  const renderProfile = () => (
    <Card title="Profile">
      <div className="grid gap-5 sm:grid-cols-[150px_minmax(0,1fr)]">
        <div className="rounded-md border border-slate-200 bg-slate-50 p-4">
          {profileForm.avatar_url ? (
            <img
              src={profileForm.avatar_url}
              alt={profileForm.full_name || "Profile avatar"}
              className="mx-auto h-20 w-20 rounded-full object-cover ring-1 ring-slate-200"
            />
          ) : (
            <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-slate-900 text-base font-semibold text-white">
              {initials(profileForm.full_name)}
            </div>
          )}
          <div className="mt-4 grid gap-2">
            <input
              id="profile-avatar-upload"
              type="file"
              accept="image/*"
              className="hidden"
              onChange={uploadProfileAvatar}
            />
            <Button
              icon={Upload}
              className="w-full"
              busy={saving === "profile-avatar"}
              onClick={() => document.getElementById("profile-avatar-upload")?.click()}
            >
              Upload
            </Button>
            <Button
              variant="danger"
              icon={Trash2}
              className="w-full"
              busy={saving === "profile-avatar"}
              disabled={!profileForm.avatar_url}
              onClick={removeProfileAvatar}
            >
              Remove
            </Button>
          </div>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Full Name">
            <Input
              value={profileForm.full_name}
              onChange={(event) => setProfileForm((current) => ({ ...current, full_name: event.target.value }))}
            />
          </Field>
          <Field label="Email">
            <Input value={profileForm.email} disabled />
          </Field>
          <Field label="Currency">
            <Select
              value={profileForm.currency}
              onChange={(event) => setProfileForm((current) => ({ ...current, currency: event.target.value }))}
            >
              {currencies.map((currency) => (
                <option key={currency} value={currency}>{currency}</option>
              ))}
            </Select>
          </Field>
        </div>
      </div>
    </Card>
  );

  const renderSecurity = () => (
    <div className="space-y-5">
      <Card title="Security">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="rounded-md border border-slate-200 bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-sm font-semibold text-slate-900">
              <Lock size={15} />
              Login Providers
            </div>
            <div className="mt-3 flex flex-wrap gap-2">
              <Badge tone={security?.providers?.email_password ? "active" : "revoked"}>
                Email {security?.providers?.email_password ? "On" : "Off"}
              </Badge>
              <Badge tone={security?.providers?.google ? "active" : "revoked"}>
                Google {security?.providers?.google ? "On" : "Off"}
              </Badge>
            </div>
          </div>
          <div className="rounded-md border border-slate-200 bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-sm font-semibold text-slate-900">
              <Shield size={15} />
              Role
            </div>
            <div className="mt-3 text-sm font-medium text-slate-900">{titleCase(security?.role || "analyst")}</div>
          </div>
        </div>
      </Card>
      <Card title="Change Password">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Current Password">
            <Input
              type="password"
              value={passwordForm.currentPassword}
              onChange={(event) => setPasswordForm((current) => ({ ...current, currentPassword: event.target.value }))}
            />
          </Field>
          <Field label="New Password">
            <Input
              type="password"
              value={passwordForm.newPassword}
              onChange={(event) => setPasswordForm((current) => ({ ...current, newPassword: event.target.value }))}
            />
          </Field>
        </div>
      </Card>
    </div>
  );

  const renderTeam = () => (
    <div className="space-y-5">
      <Card
        title="Team Members"
        action={
          isOwner ? (
            <Button icon={UserPlus} variant="primary" onClick={() => setShowInviteModal(true)}>
              Invite Member
            </Button>
          ) : null
        }
        footer="Members can work with clients, reports, Meta connections, activity, and operational settings."
      >
        <div className="mb-5">
          <h2 className="text-lg font-semibold text-slate-950">Team</h2>
          <p className="mt-1 text-sm text-slate-500">
            Manage who can access this workspace.
          </p>
        </div>

        {team.members.length ? (
          <div className="overflow-hidden rounded-lg border border-slate-200">
            <table className="w-full text-left text-sm">
              <thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3">Name</th>
                  <th className="px-4 py-3">Email</th>
                  <th className="px-4 py-3">Role</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Joined date</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {team.members.map((member) => (
                  <tr key={member.id}>
                    <td className="px-4 py-3 font-medium text-slate-950">{member.name}</td>
                    <td className="px-4 py-3 text-slate-600">{member.email}</td>
                    <td className="px-4 py-3">
                      <Badge tone={member.role}>{titleCase(member.role)}</Badge>
                    </td>
                    <td className="px-4 py-3">
                      <Badge tone={member.status}>{titleCase(member.status)}</Badge>
                    </td>
                    <td className="px-4 py-3 text-slate-500">
                      {member.joined_at ? formatDateTime(member.joined_at) : "Not available"}
                    </td>
                    <td className="px-4 py-3 text-right">
                      {isOwner && member.role !== "owner" ? (
                        <Button
                          variant="danger"
                          icon={Trash2}
                          busy={saving === `remove-member-${member.id}`}
                          onClick={() => removeMember(member)}
                        >
                          Remove
                        </Button>
                      ) : (
                        <span className="text-xs text-slate-400">-</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">
            No team members found.
          </div>
        )}
      </Card>

      <Card title="Pending Invitations">
        {team.invites.length ? (
          <div className="overflow-hidden rounded-lg border border-slate-200">
            <table className="w-full text-left text-sm">
              <thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3">Email</th>
                  <th className="px-4 py-3">Role</th>
                  <th className="px-4 py-3">Invited by</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Expires</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {team.invites.map((invite) => (
                  <tr key={invite.id}>
                    <td className="px-4 py-3 font-medium text-slate-950">{invite.email}</td>
                    <td className="px-4 py-3">
                      <Badge tone={invite.role}>{titleCase(invite.role)}</Badge>
                    </td>
                    <td className="px-4 py-3 text-slate-600">
                      {invite.invited_by?.name || invite.invited_by?.email || "Unknown"}
                    </td>
                    <td className="px-4 py-3">
                      <Badge tone={invite.status}>{titleCase(invite.status)}</Badge>
                    </td>
                    <td className="px-4 py-3 text-slate-500">
                      {invite.expires_at ? formatDateTime(invite.expires_at) : "Not available"}
                    </td>
                    <td className="px-4 py-3">
                      {isOwner ? (
                        <div className="flex justify-end gap-2">
                          <Button
                            icon={RefreshCw}
                            busy={saving === `resend-invite-${invite.id}`}
                            onClick={() => resendInvite(invite)}
                          >
                            Resend
                          </Button>
                          {invite.status === "pending" && (
                            <Button
                              variant="danger"
                              icon={Trash2}
                              busy={saving === `revoke-invite-${invite.id}`}
                              onClick={() => revokeInvite(invite)}
                            >
                              Revoke
                            </Button>
                          )}
                        </div>
                      ) : (
                        <span className="block text-right text-xs text-slate-400">-</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">
            No pending invitations.
          </div>
        )}
      </Card>

      {showInviteModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 px-4">
          <form
            onSubmit={sendInvite}
            className="w-full max-w-md rounded-xl border border-slate-200 bg-white shadow-xl"
          >
            <div className="border-b border-slate-100 px-5 py-4">
              <h3 className="text-sm font-semibold text-slate-950">Invite Member</h3>
              <p className="mt-1 text-sm text-slate-500">
                Send a workspace invitation by email.
              </p>
            </div>
            <div className="space-y-4 px-5 py-5">
              <Field label="Email address">
                <Input
                  autoFocus
                  type="email"
                  value={inviteEmail}
                  onChange={(event) => setInviteEmail(event.target.value)}
                  placeholder="teammate@agency.com"
                />
              </Field>
              <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-600">
                Role: <span className="font-semibold text-slate-900">Member</span>
              </div>
            </div>
            <div className="flex justify-end gap-2 border-t border-slate-100 px-5 py-4">
              <Button
                type="button"
                onClick={() => {
                  setShowInviteModal(false);
                  setInviteEmail("");
                }}
              >
                Cancel
              </Button>
              <Button type="submit" variant="primary" busy={saving === "team-invite"}>
                Send invite
              </Button>
            </div>
          </form>
        </div>
      )}
    </div>
  );

  const renderBilling = () => (
    <Card title="Billing">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <CreditCard size={16} className="text-slate-500" />
            <div className="text-sm font-semibold text-slate-950">{billing?.plan || "Early Access"}</div>
            <Badge tone={billing?.status || "trial"}>{titleCase(billing?.status || "trial")}</Badge>
          </div>
          <div className="mt-2 text-sm text-slate-500">
            {billing?.renewal_label || "Billing will be enabled before public launch."}
          </div>
        </div>
        <Button disabled>Manage Billing</Button>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {[
          ["Clients", billing?.usage?.clients || 0],
          ["Reports", billing?.usage?.active_reports || 0],
          ["Ad accounts", billing?.usage?.connected_ad_accounts || 0],
          ["Meta profiles", billing?.usage?.connected_meta_profiles || 0],
          ["Seats", billing?.usage?.seats || 1],
        ].map(([label, value]) => (
          <div key={label} className="rounded-md border border-slate-200 bg-slate-50 p-3">
            <div className="text-xs text-slate-500">{label}</div>
            <div className="mt-1 text-xl font-semibold text-slate-950">{value}</div>
          </div>
        ))}
      </div>
    </Card>
  );

  const content = {
    workspace: renderWorkspace,
    team: renderTeam,
    "meta-connections": renderMeta,
    "report-defaults": renderEmailSettings,
    notifications: renderNotifications,
    profile: renderProfile,
    security: renderSecurity,
    billing: renderBilling,
  };

  return (
    <div className="settings-page flex h-full min-h-0 flex-col bg-[var(--bg-app)]">
      <div className="flex h-[52px] shrink-0 items-center justify-between border-b border-slate-200 bg-white px-5 dark:border-slate-800 dark:bg-slate-950/80">
        <h1 className="text-sm font-semibold text-slate-950 dark:text-slate-50">Settings</h1>
        <div className="flex items-center gap-2">
          {error && <Badge tone="expiring_soon">Needs attention</Badge>}
          <Button
            variant={canSave ? "primary" : "muted"}
            icon={Save}
            busy={["workspace", "profile", "email-settings", "notifications", "security"].includes(saving)}
            disabled={!canSave}
            onClick={saveActiveSection}
          >
            Save Changes
          </Button>
        </div>
      </div>

      <div className="grid min-h-0 flex-1 grid-cols-[180px_minmax(0,1fr)]">
        <aside className="border-r border-slate-200 bg-[#F2F2F0] px-3 py-5 dark:border-slate-800 dark:bg-slate-950">
          <div className="space-y-1">
            {sections.map((section) => {
              const active = activeSection === section.id;
              const Icon = section.icon;

              return (
                <button
                  key={section.id}
                  type="button"
                  onClick={() => setSection(section.id)}
	                  className={`flex w-full items-center gap-2.5 rounded-xl border px-3 py-2 text-left text-sm transition ${
	                    active
	                      ? "border-slate-200 bg-white font-medium text-slate-950 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-50"
	                      : "border-transparent text-slate-600 hover:bg-white/70 hover:text-slate-950 dark:text-slate-400 dark:hover:bg-slate-900/70 dark:hover:text-slate-100"
	                  }`}
                >
                  <Icon
	                    size={15}
	                    strokeWidth={1.8}
	                    className={active ? "text-slate-900 dark:text-slate-100" : "text-slate-500 dark:text-slate-500"}
                  />
                  <span>{section.label}</span>
                </button>
              );
            })}
          </div>
        </aside>

        <main className="min-h-0 overflow-y-auto px-6 py-5">
          <div className={activeSection === "meta-connections" ? "max-w-[980px]" : "max-w-[760px]"}>
            {notice && <Notice>{notice}</Notice>}
            {error && <Notice type="error">{error}</Notice>}

            {loading ? (
              <Card title={sectionTitle}>
                <CardSkeleton rows={5} className="border-0 bg-transparent p-0 shadow-none" />
              </Card>
            ) : (
              content[activeSection]?.()
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
